<?php
return [

    // PRIVACITY

    'privacity' => [
        'header_subtitle' => 'COPPA COCKTAILS',
        'header_title' => 'PRIVACY STATEMENT',
        'title' => 'PRIVACY & COOKIE POLICY 01/06/2019',
        'text' => "
            <p>This privacy policy sets out how Coppa Cocktails B.V. uses and protects any information that you give when using this website or contacting us on social media. Coppa Cocktails B.V. is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified using this website or our social media, you can be assured that it will only be used in accordance with this privacy statement. Coppa Cocktails B.V. may change this policy from time to time by updating this page. You should check this page from time to time to ensure that you are happy with any changes.</p>
            <p>DATA INPUT: WHAT WE COLLECT WHEN YOU VISIT OUR WEBSITE</p>
            <p>You can visit our website without providing any personal data, exception of ensuring legal drinking age. We only record data in so-called server log-files, such as the name of the file accessed, the date and time of access. the data volume transferred and the requesting provider. This data will only be used to ensure proper functioning of the page and to improve our service, but cannot be traced back to you.</p>
            <p>DATA COLLECTION AND USE: WHAT WE DO WITH THE INFORMATION WE GATHER</p>
            <p>We collect personal data when it is freely provided by you within the context of making contact with us. (e.g. via e-mail or subscription to our newsletter) The specific data gathered is that provided on the various information forms. We use the data provided by you for administration purposes and to process your queries.</p>
            <p>If you subscribe to our newsletter we use the data required for this purpose or that which is separately provided by you in order to forward our newsletter to you. You may unsubscribe from the newsletter at any time via a link provided for this purpose within the newsletter of via the contact facility set out below.</p>
            <p>DATA: DISCLOSURE AND SECURITY</p>
            <p>Once we have received your personal data, we will use strict procedures and security features to prevent unauthorized access to it.</p>
            <p>We keep your personal data for no longer than necessary for the purposes for which the personal data is processed. The length of time we retain personal data for depends on the purposes for which we collect and use it and/or as required to comply with applicable laws and to establish, exercise or defend our legal rights.</p>
            <p>We do not sell your personal data to others and we never share your data unless obliged by applicable laws.</p>
            <p>DATA: HOW WE USE COOKIES</p>
            <p>On many pages we use cookies in order to enhance the attractiveness of our website and to enable the proper utilization of certain functions. This incorporates the use of small text files which are stored on your device, that save specific settings and data regarding the exchange between your browser and our system. Some of the cookies used by us will be deleted at the end of your browser session, i.e. once your browser has been closed (so- called session cookies). Other cookies remain on your device and enable us to recognize your browser on your next visit (persistent cookies).</p>
            <p>Cookies do not contain any personal data and therefore cannot be assigned to any user. Based on the cookie-technology we only received anonymized information, e.g. about the website that led you to our shop, which pages have been viewed on our website etc. Please note that some cookies are already placed as soon as you enter our website.</p>
            <p>You may configure your browser such that you are informed when any cookies are placed and decide in individual cases whether or not you wish to accept them, or you may reject cookies for specific cases or in general. Should you reject any cookies the functionality of our website may be compromised.</p>
            <p>Below we present information on cookies we use and how you can customize your browser in that respect.</p>
            <p>1. Necessary cookies: These cookies are necessary to enable you to use our website. This includes e.g. cookies that enable you to log into the customer area or add items to your shopping cart.</p>
            <p>2. Analytical / performance cookies: These cookies enable collecting anonymized data about user behavior on our website. We analyze them e.g. to improve the functionality of our website and recommend you products that will be interesting to you.</p>
            <p>3. Functionality cookies: These cookies are used for certain features of our website, e.g. to improve the website’s navigation, or deliver to you customized and relevant information.</p>
            <p>4. Targeting cookies: We DO NOT place these cookies.</p>
            <p>5. Third-party cookies: We DO NOT place these cookies.</p>
            <p>How can I change cookie settings in my browser?<br>Every browser has a different policy for managing the cookie settings. The browser’s policy is described in the Help menu of every browser and explains how you can change your cookie settings.</p>
            <p>DATA: USE OF GOOGLE ANALYTICS FOR WEB ANALYSIS PURPOSES</p>
            <p>This website uses Google (Universal) Analytics, a web analysis service provided by Google Inc. (www.google.com). Google (Universal) Analytics uses methods which enable an analysis of your use of the website, through cookies for example, text files stored on your computer. The information created about your use of this website is generally transferred to a Google server in the US and saved there. Activating the IP anonymization on this website will cause the IP address to be shortened before transfer within the member states of the European Union or in other contract states of the agreement about European Economic Area. Only in exceptional cases will the full IP address be transferred to a Google server in the US and shortened there. The anonymous IP address transferred from your browser to Google Analytics will not be joined with other data logged by Google.</p>
            <p>DATA: LINKS TO OTHER WEBSITES</p>
            <p>Our website may contain links to other websites of interest. However, once you have used these links to leave our site, you should note that we do not have any control over that other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. You should exercise caution and look at the privacy statement applicable to the website in question.</p>
            <p>DATA: CONTROLLING YOUR PERSONAL INFORMATION</p>
            <p>You are entitled to access your personal information stored by us at no charge, including the right to correct, block or delete such data. Please use the contact facility set out below should you have any queries concerning the collection, processing or exploitation of your personal data, or should you wish to access, correct, block or delete any data, or should you wish to withdraw any approval provided for or object any use of such data.</p>
            <p>The practices described in this privacy policy statement are current personal data protection policies, as of 25 May 2018.</p>
        ",
    ],

    'websiteterms' => [
        'header_subtitle' => 'COPPA COCKTAILS',
        'header_title' => 'WEBSITE TERMS & CONDITIONS',
        'title' => 'TERMS & CONDITIONS',
        'text' => "
            <p>By entering this website you agree to the following terms and conditions (“terms”) and to the Privacy Policy. If you do not accept these terms, please leave this website now.</p>
            <p><strong>1. MINIMUM AGE</strong></p>
            <p>This website is not intended to be accessed if you are under 18 years old or below the minimum legal age for lawfully purchasing alcohol in the country, state, province or territory from which you are viewing this website. Before accessing these sections of the website, you will be asked to confirm your age.</p>
            <p><strong>2. INTELLECTUAL PROPERTY</strong></p>
            <p>All intellectual property rights in the content of this website (including without limitation trade- marks, images and logos) are either owned by us or are used by us under license, and are reserved to us. You acquire no rights in the content of this website except the limited right to use the website in accordance with the terms. When the content has been pulled through from social networking sites such as Facebook, Instagram and YouTube then it will be governed by the rights of those websites. You shall retain all of your ownership rights in your user submissions, but you are required to grant limited rights to Coppa Cocktails B.V. and other users of the website. In return for using the website and the services, you grant Coppa Cocktails B.V. a non-exclusive, irrevocable, worldwide, transferable license (with full right to sub-license) to use your user submissions in any media format and through any media channel in perpetuity and free of charge. Such use shall include reproducing, copying, editing, adapting, making derivative works from, making available for download, synchronizing, displaying, publicly performing, transmitting, broadcasting, publishing, distributing, sub-licensing and deleting your user submissions.</p>
            <p><strong>3. CONTENT DISCLAIMER</strong></p>
            <p>Your use of this website (including downloading material or links to other websites) and your use and reliance on content published on this website are at your own risk. To the extent permitted by applicable law, we expressly exclude any representations, conditions, terms or warranties regarding merchantability, satisfactory quality, fitness for purpose or reasonable care and skill which might otherwise be implied or incorporated into these terms, whether by statute, law or otherwise.</p>
            <p>Except where it is expressly stated to the contrary, we do not represent or warrant:</p>
            <p>· the accuracy or completeness of the material published on this website;</p>
            <p>· the compatibility of this website with your computer system and software;</p>
            <p>· that this website is free from infection in the nature of a virus.</p>
            <p><strong>4. USE OF THIS WEBSITE</strong></p>
            <p>You are welcome to use this website in accordance with these terms and may print and/or download information from this website for your personal, non-commercial use.</p>
            <p>You may not link this website to any other website, or frame any part of this website, without our prior agreement.</p>
            <p>You may not hack this website, use this website to transmit computer viruses or use this website for any illegal purposes.</p>
            <p>You may not misrepresent or amend content that you copy from this website or use such content without publishing the copyright and other proprietary notices we use in connection with such content, in the same manner and form as used on this website.</p>
            <p>If you are in breach of these terms or our Privacy Policy we may suspend or block your access to this website.</p>
            <p><strong>5. LINKS TO OTHER WEBSITES</strong></p>
            <p>Links to other websites are provided for your convenience. We do not endorse or approve these websites or their operators and you download, browse and use such websites at your own risk and without any liability on our part.</p>
            <p><strong>6. AMENDMENTS</strong></p>
            <p>We may amend, modify, update or discontinue the operation of this website or any content published on it at any time without prior notice to you. We may also amend these terms from time to time.</p>
            <p><strong>7. LIMITATION OF OUR LIABILITY</strong></p>
            <p>We shall not be liable for any loss or damage incurred by you, whatsoever, which may have been caused by your use or attempted use of this website or any content published on it.</p>
            <p><strong>8. GOVERNING LAW AND INTERPRETATION</strong></p>
            <p>If any provision of these terms is held to be void, voidable, illegal or otherwise unenforceable; this shall not affect the validity, legality and enforceability of the remaining provisions of these terms.</p>
            <p>These terms and conditions are governed by the laws of The Netherlands.</p>
        ",
    ],

    'generalterms' => [
        'header_subtitle' => 'COPPA COCKTAILS',
        'header_title' => 'GENERAL TERMS AND CONDITIONS OF SALE AND DELIVERY',
        'title' => 'General Terms and Conditions of Sale and Delivery',
        'text' => "
            <p><strong>Version valid from 1 October 2021</strong></p>
            <p><strong>1. Definitions</strong></p>
            <p>1.1. General Terms and Conditions: These general terms and conditions of sale and delivery.</p>
            <p>1.2. Buyer: The buyer or potential buyer of Products.</p>
            <p>1.3. Products: The goods and services offered, sold and (to be) delivered by Seller to Buyer, as well as work performed or to be performed.</p>
            <p>1.4. Agreement: Each agreement between Seller and Buyer, including the General Terms and Conditions, concerning the sale and delivery of Products by Seller.</p>
            <p>1.5. Seller: Coppa Cocktails B.V. or any affiliated company, which has declared the General Terms and Conditions applicable and has entered into an Agreement with Buyer.</p>
            <p><strong>2. General</strong></p>
            <p>2.1. The General Terms and Conditions apply to the formation, contents and execution of the Agreement, as well as to all other legal acts and relationships between Seller and Buyer. </p>
            <p>2.2. In the event of any conflict or inconsistency between them, the terms of these General Terms and Conditions will take precedence over any other terms purported to apply to the Agreement and shall take precedence over any terms set out in any ordering of other documents purported by Buyer to apply. Any and all provisions deviating from or supplementary to the General Terms and Conditions shall only have effect if such provisions have been accepted in writing by Seller and shall only be applicable to the relevant Agreement. </p>
            <p>2.3. The invalidity of one or several provisions of the General Terms and Conditions shall not affect the validity of the remaining provisions. Should any provision of the General Terms and Conditions or the Agreement be invalid for whatever reason, the parties will negotiate on the contents of a new provision, which shall be similar to the contents of the invalid provision as much as possible. </p>
            <p>2.4. In the event of resale or distribution of the Products by Buyer, Buyer is obliged to impose on its own buyer, if and insofar as applicable, the rights and obligations Buyer has towards Seller under Articles 8, 9, 10 and 14 of these General Terms and Conditions by way of a perpetual clause.</p>
            <p><strong>3. Agreement</strong></p>
            <p>3.1. Quotations made by Seller do not constitute a legally binding offer and may be revised or revoked by Seller at any time prior to the conclusion of the Agreement, even when a term for acceptance has been given by Seller. Unless Seller has indicated otherwise in writing, a quotation will be deemed to be revoked in any case after a period of 30 calendar days has lapsed from the date of the quotation.</p>
            <p>3.2. An Agreement will only be concluded when Seller accepts, in writing (scanned or original) or an explicit and unambiguous acceptance by e-mail, or a verbal or written order from Buyer, within 2 days of receipt thereof or when Seller has commenced execution of the order, which is perceptible to Buyer.</p>
            <p>3.3. Seller may require a written confirmation from Buyer of an order placed by telephone, in the form of a copy, signed for approval by Buyer, of the quotation, order confirmation or acceptance submitted by Seller, as the case may be.</p>
            <p>3.4. No amendment of the Agreement will be effective unless it is signed by both Seller and Buyer.</p>
            <p><strong>4. Price</strong></p>
            <p>4.1. All prices provided by Seller in price lists, catalogues, brochures, information on websites, quotations, order confirmations, written acceptances or otherwise, are net prices and are thus exclusive of turnover tax (VAT) and any other levies imposed by the relevant authorities, and of any other amount paid for by Seller to any third party for the benefit of or at the request of Buyer in connection with the execution of the Agreement (including for instance transport costs). If applicable, all such taxes, levies and amounts will be borne by Buyer.</p>
            <p>4.2. Seller will have the right to pass on to Buyer all increases in costs caused by the implementation or amendment of any statutory provision pertaining to applicable levies, taxes or permits during the execution of the Agreement.</p>
            <p>4.3  Seller shall be entitled to adjust the applicable prices at any time by providing written notice to Buyer at least 3 months in advance. If Buyer does not wish to agree to such an adjustment, Buyer shall, within 30 days after the notice, be entitled to terminate the Agreement before the date on which the adjustment would have become effective.</p>
            <p>4.4. Any discounts given by Seller refer solely to the net price and are only applicable to the relevant Agreement.</p>
            <p><strong>5. Authorities of Seller</strong></p>
            <p>5.1. Seller may determine a minimum purchase quantity for each Product, below which Seller will not enter into an Agreement for said Product.</p>
            <p>5.2. The manner in which the Products are packed is determined by Seller and may be changed at any time. In such event, Seller will, insofar as possible, inform Buyer thereof in advance.</p>
            <p><strong>6. Delivery</strong></p>
            <p>6.1. Seller will deliver “ex works” (Incoterms 2020) at Seller’s business locations in Zevenaar, the Netherlands. Every other manner of delivery must be agreed upon in writing.Unless otherwise explicitly agreed upon in writing, Seller will determine the manner of dispatch, transport and the like, without Seller bearing any responsibility whatsoever with regard thereto.</p>
            <p>6.2. Empty packaging, charged to Buyer by Seller, will be taken back by Seller at the price charged, provided that the packaging concerned is received back by Seller undamaged and in good condition, postage paid. For packaging received back at a later date than the agreed return date, a monthly rent is charged , amounting to 10% of the price charged, in which respect each part of a month is counted as a full month.</p>
            <p>6.3. In mutual consultation between Seller and Buyer, a period will be fixed within which Seller will deliver to Buyer. The period referred to will not commence until Seller has received the quotation, order confirmation or written acceptance, as the case may be, signed for approval by Buyer, and all other information necessary for the delivery. If the term of delivery or collection is exceeded, Buyer will not be entitled to any compensation, nor will such non-compliance with the term of delivery constitute any ground for refusal of the goods and/or non-payment.</p>
            <p>6.4. Seller will at all times have the right to deliver the Product ordered by Buyer in partial deliveries. The provisions of the preceding paragraph also apply to partial deliveries. Any partial delivery is considered to be an independent delivery, so that any claims concerning a partial delivery will not affect earlier or later partial deliveries. Invoicing will take place per partial delivery. </p>
            <p>6.5. The delivery period will be extended by the period in which Seller, as a result of force majeure, is unable to deliver. If the extension of the original period is more than one month, then both Seller and Buyer will have the right to dissolve the Agreement or -in the event of partial execution of the Agreement- the part thereof that has not yet been executed, by means of a written statement to that effect to the other party. Dissolution pursuant to this article does not entitle either party to any compensation whatsoever. ‘Force majeure’ in this respect includes: war, riots and other types of mobilisation, fire and accidents, machine or other breakdowns in the factory, whether or not as a result of errors made by the employees of Seller, transport impediments, flooding, frost and other weather conditions, government measures prohibiting or hindering delivery, failure by suppliers to supply or to supply in good time, failure by carriers or forwarding agents to supply in good time, failures on the part of auxiliary persons engaged by Seller, illness, disturbances, sit-down strikes and similar actions and all disruptions of the normal continuation of business operations of Seller, which are a result of circumstances beyond the control of Seller and which temporarily or permanently hinder the performance of the Agreement or make it considerably more difficult or expensive to do so.</p>
            <p>6.6. The risk for loss of or damage to the Products will pass to Buyer from the time of delivery in accordance with this Article 6.</p>
            <p>6.7. Buyer is obliged to cooperate in the delivery, as well as to receive the Products delivered. In the event of failure on the part of Buyer to cooperate in the delivery and receive the Products in good time, Seller will have the right to charge Buyer for additional costs incurred (including for instance storage costs).</p>
            <p><strong>7. Quality and usability; complaints</strong></p>
            <p>7.1. Seller does not guarantee that its Products are bottled, labelled or packed in accordance with the legal requirements applicable in all territories of import or re-sale. Without a written undertaking to the contrary, the importation and sale of its Products in territories other than the Netherlands is therefore done at the exclusive risk of Buyer importing or re-selling Products into such territories. Furthermore Buyer agrees to indemnify Seller against all claims, costs or charges that Seller may become liable for in connection with such import or re-sale of the Products.</p>
            <p>7.2. Buyer is obliged to inspect Products upon delivery for any defects with regard to quality, packaging and the like. Buyer must submit any complaint to Seller in writing within fourteen days of the time of delivery. In the event that a defect cannot be determined immediately upon careful inspection, the complaint must be made known to Seller in writing within 14 days of the time the defect should reasonably have been known to Buyer, in default of which Buyer will lose all claims against Seller as regards said defect. Submitting complaints does not entitle Buyer to suspend its payment obligation(s).</p>
            <p>7.3. In the event that timely filed complaints are accepted by Seller as well-founded, Seller will send Buyer, at Seller’s discretion, a credit note for the net invoice amount of the relevant Products that do not comply with the Agreement, or Seller will perform anew as soon as possible.</p>
            <p><strong>8. Labelling and packaging; promotional materials</strong></p>
            <p>8.1. Without the prior written permission of Seller, Buyer is not permitted to offer or (re)sell the Products delivered in any packaging and/or with any labelling other than the original packaging and/or labelling of Seller. However, Buyer may offer or (re)sell individual Products that have been delivered in bulk packaging, provided the individual Products are offered or (re)sold in the original packaging and/or labelling of Seller.</p>
            <p>8.2. Furthermore, Buyer is not permitted, without the prior written permission of Seller, to use the distinguishing characteristics protected by Seller by copyright and trademark rights, other than by (re)selling the Products delivered.</p>
            <p>8.3. The promotional materials that Seller may make available to Buyer, whether free of charge or otherwise, in support of the sale of the Products, shall at all times remain the property of Seller. Upon Seller's first request, Buyer shall return said promotional materials to Seller carriage-free and for the own risk of Buyer.</p>
            <p>8.4. Buyer is not permitted to create and/or use or have third parties create and/or use promotional or other marketing materials, indications and/or communications for the Products without Seller's prior written approval. Buyer will also impose this obligation on its customers.</p>
            <p><strong>9. Intellectual property</strong></p>
            <p>9.1. As between Seller and Buyer, all intellectual property rights, in whatever form, embodied within:</p>
            <p>(a) the Products; and,</p>
            <p>(b) any promotional or other supporting materials provided to Buyer by Seller in connection with the Products or otherwise under or in connection with the Agreement;</p>
            <p>(c) or otherwise arising from the performance of the Agreement by Seller;</p>
            <p>hereinafter, in this provision, collectively referred to as: the \"Property\"),</p>
            <p>shall belong to Seller, unless explicitly agreed otherwise. Buyer declares to be familiar with the intellectual property rights in the Property from and/or used by Seller. Buyer shall only acquire the rights of use expressly granted in these General Terms and Conditions and by law. Any other or more extensive right of Buyer shall be excluded. A right of use to which Buyer is entitled shall be non-exclusive.</p>
            <p>9.2 Upon resale/onward supply, Buyer will market the Products exclusively under the intellectual property rights established by Seller and demand from its purchaser by way of perpetual clause that the Products be resold only under those intellectual property rights.</p>
            <p>9.3 Buyer declares not to infringe any of the intellectual property rights established by Seller and to inform Seller immediately of any infringement. Buyer agrees to use its best efforts to assist Seller to the extent necessary to protect the rights in the intellectual property rights. If any infringement by a third party of the intellectual property rights in the Property or any other unlawful act prejudicial to the interest of Seller comes to its attention, Buyer shall promptly notify Seller of such act. Seller has the sole right and option to undertake and conduct the defence of any action, claim or suit so brought. Buyer shall reasonably cooperate with Seller in any action, claim or suit undertaken and conducted by Seller.</p>
            <p>9.4 Any intellectual property rights under or in connection with the Agreement which are owned by Buyer are hereby transferred in advance by Buyer to Seller at the time they arise, which transfer is hereby accepted by Seller in advance. To the extent that the transfer of these rights  would at any time require a further deed, Buyer irrevocably authorises Seller in advance to draw up any such deed and to sign it on behalf of Buyer, without prejudice to Buyer's obligation to cooperate in the transfer of these rights at Seller’s first request.</p>
            <p>9.5 If there is a difference of opinion between the Parties concerning the intellectual property rights referred to in this Article, it will be assumed, in the absence of proof to the contrary, that Seller is entitled to those intellectual property rights.</p>
            <p>9.6 Buyer hereby waives towards Seller any moral rights (including personal rights) to which he, Buyer and Buyer’s personnel, may be entitled as referred to in the Dutch Copyright Act, to the extent that the applicable regulations permit such a waiver.</p>
            <p>9.7 Buyer indemnifies Seller against claims from third parties in respect of (alleged) infringement of intellectual property rights of those third parties, including similar claims relating to knowledge, unlawful competition and the like, in connection with the rights transferred to Seller in accordance with this Article</p>
            <p><strong>10. Clearance of customs documents</strong></p>
            <p>At the time Buyer or Buyer’s carrier takes receipt of the customs documents for a batch of Products that are delivered with customs documents, Buyer assumes liability to ensure (full) clearance is given. If and at such time as Buyer or Buyer’s carrier signs the CMR waybill (waybill based on the United Nations Convention on the Contract for the International Carriage of Goods by Road) or the standard consignment note belonging to the relevant consignment in acknowledgement of receipt, this will constitute comprehensive proof for receipt of the customs documents stated thereon. Buyer will indemnify Seller against all claims from third parties, including the tax authorities and customs, resulting from the fact that (full) clearance of the relevant customs documents, as referred to on the CMR waybill or the standard consignment note, was not obtained. The basis for this obligation to indemnify is, in so far as this concerns excise duty and other levies, the document whereon an obligation to pay is laid down or imposed, temporarily or otherwise. In any case, the obligation to indemnify, in so far as this concerns excise duty and other levies, is applicable from the time Seller has delivered the customs documents, in accordance with this stipulation, to Buyer or Buyer’s carrier.</p>
            <p><strong>11. Limitation of liability</strong></p>
            <p>11.1. Seller, as well as Seller’s subordinates and any third party engaged by Seller for whom Seller is liable, shall not be obliged towards Buyer to compensate for costs, damages and/or interests resulting and/or arising from personal injury or damage to goods caused by the Products, if and in so far as this is not due to the wilful intent or gross negligence on the part of the management of Seller.</p>
            <p>11.2. Seller, as well as Seller’s subordinates and any third party engaged by Seller, shall not be liable towards Buyer for damage and/or loss caused by errors or omissions of third parties or by chemical effects or induction of materials not used by Seller.</p>
            <p>11.3. In the event that Buyer has delivered products to a third party, which partly consist of the Products delivered by Seller to Buyer, Seller shall not be liable for product liability ensuing from a defect in said products delivered by Buyer to said third party, except if and insofar as Buyer proves that the personal injury or damage to goods was solely caused by the Products delivered by Seller, in which latter event the first paragraph of this Article 11 shall apply.</p>
            <p>11.4. The liability of Seller shall in any case always be limited to direct damages to a maximum amount equal to the net price (the price as referred to in Article 3 of the General Terms and Conditions) of that Agreement, or, in the case of a partial delivery, of that part of the Agreement to which the case of damage is most closely related.</p>
            <p>11.5. Buyer will indemnify Seller, Seller’s subordinates and any third party engaged by Seller, against all and any claims enforced by third parties against Seller by reason of the circumstances referred to in the previous paragraphs of this Article 11. Buyer will pay, in full, all damage and/or costs, connected with such claims, including any costs for legal assistance. </p>
            <p>11.6. Under no circumstance is Seller liable for damage consisting of loss of turnover or goodwill or business, decline in proceeds, loss of profit or anticipated savings, loss of use, or for other special, indirect or consequential damage whatsoever or howsoever.</p>
            <p><strong>12. Terms of payment</strong></p>
            <p>12.1. All payments must be made in euros upon delivery, unless otherwise agreed upon in writing.</p>
            <p>12.2. All payments must be made without any discount whatsoever. Buyer waives the right to put up the defence of set-off or to defer payment in respect of Seller or a company affiliated to the latter.</p>
            <p>12.3. Bank transfers will only become valid when the relevant amounts have been credited to the bank account of Seller.</p>
            <p>12.4. In the event that Buyer is in default of payment of the amount owed by Buyer, within the applicable payment period, as well as in the case of involuntary liquidation and moratorium on payments, all the amounts owed by Buyer to Seller will become immediately due and payable in full by operation of law, without any warning or notice of default being required thereto. In such case, all judicial and extrajudicial costs incurred at that time by Seller in order to collect the amounts due to Seller will be payable by Buyer. </p>
            <p>12.5. Extrajudicial collection costs payable by Buyer will be assessed in accordance with the Extrajudicial Collection Costs Decree (Besluit vergoeding voor buitengerechtelijke incassokosten) and amount to EUR 250 as a minimum, unless the actual extrajudicial collection costs are higher, in which case Buyer will owe the actual extrajudicial collection costs to Seller. </p>
            <p>12.6. In the event of failure to pay any amount in good time within the period agreed upon, Seller shall furthermore have the right to demand payment of interest of 1.5% per month, taking effect from the due date of the term of payment and to be calculated over the amount then due and payable, in which respect every part of a month will be counted as a full month, on the understanding that the interest charged by Seller will under no circumstance be lower than the statutory interest.</p>
            <p>12.7 Seller reserves the right to amend and/or withdraw any credit terms from time to time at its sole and absolute discretion.</p>
            <p><strong>13. Termination</strong></p>
            <p>In the event that Buyer:</p>
            <p>a) files a petition for its own bankruptcy, is declared bankrupt, assigns an estate, petitions for a moratorium on payments, or part of Buyer’s assets are seized and this is not lifted within ten days of seizure;</p>
            <p>b) is in default as regards its fulfilment of any obligation under the Agreement, and -if it is not clear beyond reasonable doubt that Buyer will not be able to remedy the situation- remains in default, even after being sent a written notice of default in which it is given 10 days to remedy the situation;</p>
            <p>c) fails to pay an invoice amount or a part thereof within the specified term; or</p>
            <p>d) discontinues its company or an important part thereof or decides to do so, Seller shall be entitled to dissolve the Agreement wholly or in part, merely by means of a written statement to that effect, and to demand the goods and Products delivered, in so far as not yet paid for, be returned or to demand payment of that part of the Agreement that has been executed or to suspend further execution of all current Agreements until full payment has been made, or to demand payment in advance and/or security for further deliveries, without prejudice to the right of Seller to full compensation for the damage and/or loss resulting and/or arising from the shortcoming(s) of Buyer and without Buyer being entitled to any compensation whatsoever.</p>
            <p><strong>14. Retention of title</strong></p>
            <p>Seller retains title to all Products delivered by Seller until such time as Buyer no longer owes Seller any sums of money, to be increased by all applicable collection costs and interest, for deliveries made to Buyer by Seller. Until such time as Buyer has fulfilled all (payment) obligations towards Seller pursuant to the Agreement, Buyer is not entitled to encumber the delivered Products or to alienate them other than in the course of Buyer’s ordinary business operations. Buyer must inform Seller promptly of any claims by or attempts on the part of third parties to get the Products subject to Seller's retention of title under their control or to seize them, and must confirm this forthwith to Seller in writing. Seller shall at all times (therefore also outside the normal business hours of Buyer or Buyer's holders) have the right to collect the delivered Products from Buyer or Buyer’s holders, or to have the Products collected, in the event that Buyer fails or Seller has reason to assume that Buyer will fail to fulfil its obligations towards Seller in full, irrespective of whether Buyer has fulfilled its (payment) obligations as regards the specific Products to be collected. Buyer and its holders are obliged to fully cooperate in this matter. At its own expense Buyer must properly insure and keep insured the Products that are subject to Seller's retention of title against ordinary operating risks.</p>
            <p><strong>15. Applicable law and competent court</strong></p>
            <p>Unless otherwise explicitly agreed upon in writing, all Agreements and all Agreements ensuing therefrom are exclusively governed by the laws of the Netherlands. All disputes arising between Buyer and Seller shall be settled by the competent court in Arnhem, the Netherlands. However, Seller shall have the right to bring a dispute before the court within whose jurisdiction Buyer has its domicile. The applicability of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded for all Agreements between Buyer and Seller.</p>

        ",
    ],

];
