version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        user: laravel
        uid: 1000
    image: web-coppacocktails-app
    container_name: web-coppacocktails-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - web-coppacocktails

  nginx:
    image: nginx:alpine
    container_name: web-coppacocktails-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-coppacocktails

  db:
    image: mariadb:10.6
    container_name: web-coppacocktails-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-web_coppacocktails}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-web_coppacocktails}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - web-coppacocktails

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: web-coppacocktails-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "8080:80"
    networks:
      - web-coppacocktails

networks:
  web-coppacocktails:
    driver: bridge 